# general
seed: 42
workers: 8
dataset_dir: "./datasets"

# train options
batch_size: 22
image_size: (256,128)

# model options
backbone: "ResNet18" # ResNet18 / ResNet34 / ResNet50 / ShuffleNetV2 / EfficientNetB0

attention_enable: True
