# general
seed: 42
workers: 8
dataset_dir: "./datasets"

# train options
batch_size: 512
image_size: (256,128)
start_epoch: 0
epochs: 80
dataset: "IceHockey"

# model options
backbone: "ResNet18" # ResNet18 / ResNet34 / ResNet50
model_path: "save/IceHockey"
model_type: "prtrei"

# loss options
learning_rate: 0.0003
weight_decay: 0.

# etc
changed_datasets: False
use_wandb: False
attention_enable: True
attention_learnable: True
attention_weights: 0.7